services:
  - name: test
    image: n8nio/n8n
    env:
      N8N_HOST: test.ghozali.biz.id
      N8N_PROTOCOL: https
      WEBHOOK_URL: https://test.ghozali.biz.id/
      N8N_EDITOR_BASE_URL: https://test.ghozali.biz.id/
      N8N_TRUST_PROXY: true
