version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-test
    restart: always
    ports:
      - "5679:5678"
    environment:
      - N8N_HOST=test.ghozali.biz.id
      - WEBHOOK_URL=https://test.ghozali.biz.id
      - N8N_EDITOR_BASE_URL=https://test.ghozali.biz.id
